"""create tables

Revision ID: 333ddec21ae4
Revises: None
Create Date: 2014-07-09 19:45:17.570693

"""

# revision identifiers, used by Alembic.
revision = '333ddec21ae4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('em_mmt_tran',
    sa.Column('mt_pr', sa.Integer(), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=40), nullable=True),
    sa.Column('content', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('callback', sa.VARCHAR(length=25), nullable=True),
    sa.Column('recipent_num', sa.VARCHAR(length=25), nullable=True),
    sa.PrimaryKeyConstraint('mt_pr')
    )
    op.create_table('em_smt_trans',
    sa.Column('mt_pr', sa.Integer(), nullable=False),
    sa.Column('content', sa.VARCHAR(length=255), nullable=True),
    sa.Column('callback', sa.VARCHAR(length=25), nullable=True),
    sa.Column('recipent_num', sa.VARCHAR(length=25), nullable=True),
    sa.PrimaryKeyConstraint('mt_pr')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('em_smt_trans')
    op.drop_table('em_mmt_tran')
    ### end Alembic commands ###
